version: 2
jobs:
  build:
    docker:
      - image: pecorarista/sdkman
        auth:
          username: pecorarista
          password: $DOCKERHUB_PASSWORD
      - image: elasticsearch:7.3.2
        environment:
          discovery.type: single-node
          network.host: _local_
          http.port: 9200
    steps:
      - checkout
      - run:
          name: Show current versions
          command: |
            source /home/circleci/.sdkman/bin/sdkman-init.sh
            sdk current
      - run:
          name: Check format
          command: |
            source /home/circleci/.sdkman/bin/sdkman-init.sh
            sbt scalafmtCheck scalafmtSbtCheck
